<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Ubah Password Berhasil</title>
        <link rel="stylesheet" href="/css/kerjaku.css" />
    </head>
    <body>
		<div class="header">
			<img src="/images/kerjaku-logo.svg"  border="0" />
		</div>
        <div class="container">
            <h3>Ubah Password</h3>
            <?php if(!empty($message)): ?>
            <em>Status: <?=$message?></em>
            <?php endif;?>
        </div>
    </body>
</html>
