<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Verification Email</title>
    </head>
    <body>
        <div class="container">
            <h1>Verifikasi Email</h1>
            <em>Status: <?=$message?></em>
        </div>
    </body>
</html>
